#!/usr/bin/env bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $current_directory"/../../../.terminal_support/colors/full_colors.colors.bash"
source $current_directory"/../../plugins/box_drawing/box_it.bash"

echo "╭─────────────────────╮"
echo "│  Background Colors  │"
echo "╰─────────────────────╯"

num_rows=16
num_cols=2
background_matrix_elements=("Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ..."\
  "Lorem ipsum dolor sit amet, conseteturV ...")

background_matrix_elements_colors=(${COLORS["WHITE_ON_BLACK"]}\
    ${COLORS["BLACK_ON_BLACK"]}\
    ${COLORS["WHITE_ON_LIGHT_BLACK"]}\
    ${COLORS["BLACK_ON_LIGHT_BLACK"]}\
    ${COLORS["WHITE_ON_RED"]}\
    ${COLORS["BLACK_ON_RED"]}\
    ${COLORS["WHITE_ON_LIGHT_RED"]}\
    ${COLORS["BLACK_ON_LIGHT_RED"]}\
    ${COLORS["WHITE_ON_GREEN"]}\
    ${COLORS["BLACK_ON_GREEN"]}\
    ${COLORS["WHITE_ON_LIGHT_GREEN"]}\
    ${COLORS["BLACK_ON_LIGHT_GREEN"]}\
    ${COLORS["WHITE_ON_YELLOW"]}\
    ${COLORS["BLACK_ON_YELLOW"]}\
    ${COLORS["WHITE_ON_LIGHT_YELLOW"]}\
    ${COLORS["BLACK_ON_LIGHT_YELLOW"]}\
    ${COLORS["WHITE_ON_BLUE"]}\
    ${COLORS["BLACK_ON_BLUE"]}\
    ${COLORS["WHITE_ON_LIGHT_BLUE"]}\
    ${COLORS["BLACK_ON_LIGHT_BLUE"]}\
    ${COLORS["WHITE_ON_MAGENTA"]}\
    ${COLORS["BLACK_ON_MAGENTA"]}\
    ${COLORS["WHITE_ON_LIGHT_MAGENTA"]}\
    ${COLORS["BLACK_ON_LIGHT_MAGENTA"]}\
    ${COLORS["WHITE_ON_CYAN"]}\
    ${COLORS["BLACK_ON_CYAN"]}\
    ${COLORS["WHITE_ON_LIGHT_CYAN"]}\
    ${COLORS["BLACK_ON_LIGHT_CYAN"]}\
    ${COLORS["WHITE_ON_WHITE"]}\
    ${COLORS["BLACK_ON_WHITE"]}\
    ${COLORS["WHITE_ON_LIGHT_WHITE"]}\
    ${COLORS["BLACK_ON_LIGHT_WHITE"]})

box_it "$num_rows" "$num_cols" "${background_matrix_elements[@]}" "${background_matrix_elements_colors[@]}"

