#!/usr/bin/env bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $current_directory"/../../colors/foreground_colors.bash"
source $current_directory"/../../plugins/box_drawing/box_it"

echo "╭─────────────────────╮"
echo "│  Foreground Colors  │"
echo "╰─────────────────────╯"

# Regular
num_rows=8
num_cols=3
default_matrix_elements=("DIM_Black" "DEFAULT_Black" "LIGHT_Black"\
  "DIM_Red" "DEFAULT_Red" "LIGHT_Red"\
  "DIM_Green" "DEFAULT_Green" "LIGHT_Green"\
  "DIM_Yellow" "DEFAULT_Yellow" "LIGHT_Yellow"\
  "DIM_Blue" "DEFAULT_Blue" "LIGHT_Blue"\
  "DIM_Purple" "DEFAULT_Purple" "LIGHT_Purple"\
  "DIM_Cyan" "DEFAULT_Cyan" "LIGHT_Cyan"\
  "DIM_White" "DEFAULT_White" "LIGHT_White")
default_matrix_elements_colors=($dim_black $black $dark_gray\
  $dim_red $red $light_red\
  $dim_green $green $light_green\
  $dim_yellow $yellow $light_yellow\
  $dim_blue $blue $light_blue\
  $dim_purple $purple $light_purple\
  $dim_cyan $cyan $light_cyan\
  $dim_light_gray $light_gray $white)

box_it "$num_rows" "$num_cols" "${default_matrix_elements[@]}" "${default_matrix_elements_colors[@]}"

# Bold
num_rows=8
num_cols=2
bold_matrix_elements=("BOLD_Black" "BOLD_LIGHT_Black"\
  "BOLD_Red" "BOLD_LIGHT_Red"\
  "BOLD_Green" "BOLD_LIGHT_Green"\
  "BOLD_Yellow" "BOLD_LIGHT_Yellow"\
  "BOLD_Blue" "BOLD_LIGHT_Blue"\
  "BOLD_Purple" "BOLD_LIGHT_Purple"\
  "BOLD_Cyan" "BOLD_LIGHT_Cyan"\
  "BOLD_White" "BOLD_LIGHT_White")
bold_matrix_elements_colors=($bold_black $bold_dark_gray\
  $bold_red $bold_light_red\
  $bold_green $bold_light_green\
  $bold_yellow $bold_light_yellow\
  $bold_blue $bold_light_blue\
  $bold_purple $bold_light_purple\
  $bold_cyan $bold_light_cyan\
  $bold_light_gray $bold_white)

box_it "$num_rows" "$num_cols" "${bold_matrix_elements[@]}" "${bold_matrix_elements_colors[@]}"

# Underlined
num_rows=8
num_cols=2
underlined_matrix_elements=("UNDERLINED_Black" "UNDERLINED_LIGHT_Black"\
  "UNDERLINED_Red" "UNDERLINED_LIGHT_Red"\
  "UNDERLINED_Green" "UNDERLINED_LIGHT_Green"\
  "UNDERLINED_Yellow" "UNDERLINED_LIGHT_Yellow"\
  "UNDERLINED_Blue" "UNDERLINED_LIGHT_Blue"\
  "UNDERLINED_Purple" "UNDERLINED_LIGHT_Purple"\
  "UNDERLINED_Cyan" "UNDERLINED_LIGHT_Cyan"\
  "UNDERLINED_White" "UNDERLINED_LIGHT_White")
underlined_matrix_elements_colors=($underlined_black $underlined_dark_gray\
  $underlined_red $underlined_light_red\
  $underlined_green $underlined_light_green\
  $underlined_yellow $underlined_light_yellow\
  $underlined_blue $underlined_light_blue\
  $underlined_purple $underlined_light_purple\
  $underlined_cyan $underlined_light_cyan\
  $underlined_light_gray $underlined_white)

box_it "$num_rows" "$num_cols" "${underlined_matrix_elements[@]}" "${underlined_matrix_elements_colors[@]}"
