#!/usr/bin/env bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $current_directory"/../../../.terminal_support/colors/full_colors.colors.bash"
source $current_directory"/../../plugins/box_drawing/box_it.bash"

echo "╭─────────────────────╮"
echo "│  Foreground Colors  │"
echo "╰─────────────────────╯"

# Regular
num_rows=8
num_cols=3
default_matrix_elements=("DIM_BLACK" "BLACK" "LIGHT_BLACK"\
  "DIM_RED" "RED" "LIGHT_RED"\
  "DIM_GREEN" "GREEN" "LIGHT_GREEN"\
  "DIM_YELLOW" "YELLOW" "LIGHT_YELLOW"\
  "DIM_BLUE" "BLUE" "LIGHT_BLUE"\
  "DIM_MAGENTA" "MAGENTA" "LIGHT_MAGENTA"\
  "DIM_CYAN" "CYAN" "LIGHT_CYAN"\
  "DIM_WHITE" "WHITE" "LIGHT_WHITE")

declare -a default_matrix_elements_colors
i=0
for element in ${default_matrix_elements[@]}; do
  default_matrix_elements_colors["$i"]=${COLORS["$element"]}
  i=$((i+1))
done

box_it "$num_rows" "$num_cols" "${default_matrix_elements[@]}" "${default_matrix_elements_colors[@]}"

# Bold
num_rows=8
num_cols=2
bold_matrix_elements=("BOLD_BLACK" "BOLD_LIGHT_BLACK"\
  "BOLD_RED" "BOLD_LIGHT_RED"\
  "BOLD_GREEN" "BOLD_LIGHT_GREEN"\
  "BOLD_YELLOW" "BOLD_LIGHT_YELLOW"\
  "BOLD_BLUE" "BOLD_LIGHT_BLUE"\
  "BOLD_MAGENTA" "BOLD_LIGHT_MAGENTA"\
  "BOLD_CYAN" "BOLD_LIGHT_CYAN"\
  "BOLD_WHITE" "BOLD_LIGHT_WHITE")

declare -a bold_matrix_elements_colors
i=0
for element in ${bold_matrix_elements[@]}; do
  bold_matrix_elements_colors["$i"]=${COLORS["$element"]}
  i=$((i+1))
done

box_it "$num_rows" "$num_cols" "${bold_matrix_elements[@]}" "${bold_matrix_elements_colors[@]}"

# Underlined
num_rows=8
num_cols=2
underlined_matrix_elements=("UNDERLINED_BLACK" "UNDERLINED_LIGHT_BLACK"\
  "UNDERLINED_RED" "UNDERLINED_LIGHT_RED"\
  "UNDERLINED_GREEN" "UNDERLINED_LIGHT_GREEN"\
  "UNDERLINED_YELLOW" "UNDERLINED_LIGHT_YELLOW"\
  "UNDERLINED_BLUE" "UNDERLINED_LIGHT_BLUE"\
  "UNDERLINED_MAGENTA" "UNDERLINED_LIGHT_MAGENTA"\
  "UNDERLINED_CYAN" "UNDERLINED_LIGHT_CYAN"\
  "UNDERLINED_WHITE" "UNDERLINED_LIGHT_WHITE")

declare -a underlined_matrix_elements_colors
i=0
for element in ${underlined_matrix_elements[@]}; do
  underlined_matrix_elements_colors["$i"]=${COLORS["$element"]}
  i=$((i+1))
done

box_it "$num_rows" "$num_cols" "${underlined_matrix_elements[@]}" "${underlined_matrix_elements_colors[@]}"

# for key in "${!COLORS[@]}"; do
  # value="${COLORS[$key]}"
  # echo "$value$key$color_off"
# done
