#!/usr/bin/env bash

current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $current_directory"/../../plugins/box_drawing/box_it.bash"

num_rows=4
num_cols=4
background_matrix_elements=(1.0 2 3 4 5 6 7 8 9 10 11.1 12 13 14 15 16)

box_it "$num_rows" "$num_cols" "${background_matrix_elements[@]}"
